version: '3'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  #alertmanager-data:
  #node_exporter-data:
services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/host'
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - :9090

  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    restart: unless-stopped
    #expose:
    #  - 3000
    ports:
      - 32882:3000
      - 32881:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  # alertmanager:
  #   image: prom/alertmanager:v0.23.0
  #   restart: unless-stopped
  #   ports:
  #     - :9093
  #   volumes:
  #     - "./alertmanager:/config"
  #     - alertmanager-data:/data
  #   command: --config.file=/config/alertmanager.yml --log.level=debug

