global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml
  
scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['localhost:9100']

  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets: [ 'alertmanager:9093' ]
